name: Build PDX With Playdate SDK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  BUILD_OUTPUT: TamaPlay

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SDK
        uses: idleberg/setup-playdate-sdk@v3.0.0

      - name: Extract Build Number
        id: extract_build_number
        run: |
          build_number=$(grep -oP '(?<=buildNumber=)\d+' Source/pdxinfo)
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV

      - name: Build Project
        run: |
          pdc Source ${{ env.BUILD_OUTPUT }}.pdx
          zip -r -9 ${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip ${{ env.BUILD_OUTPUT }}.pdx

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip

  release:
    name: Create and Upload Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract Build Number
        id: extract_build_number
        run: |
          build_number=$(grep -oP '(?<=buildNumber=)\d+' Source/pdxinfo)
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV

      - name: Verify Build Output
        run: |
          ls -la  # List files to verify presence
          if [ ! -f ./${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip ]; then
            echo "Error: Build output file not found!"
            exit 1
          fi

      - name: Create Tag and Release
        id: create_tag
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create v${{ env.BUILD_NUMBER }} ./${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip --notes "Release for build number ${{ env.BUILD_NUMBER }}" "Release for build number ${{ env.BUILD_NUMBER }}" "Release for build number ${{ env.BUILD_NUMBER }}"
