name: Build PDX With Playdate SDK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  BUILD_OUTPUT: TamaPlay

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SDK
        uses: idleberg/setup-playdate-sdk@v3.0.0

      - name: Extract Build Number
        id: extract_build_number
        run: |
          build_number=$(grep -oP '(?<=buildNumber=)\d+' Source/pdxinfo)
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV

      - name: Build Project
        run: |
          pdc Source ${{ env.BUILD_OUTPUT }}.pdx
          zip -r -9 ${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip ${{ env.BUILD_OUTPUT }}.pdx

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip

  release:
    name: Create and Upload Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract Build Number
        id: extract_build_number
        run: |
          build_number=$(grep -oP '(?<=buildNumber=)\d+' Source/pdxinfo)
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ env.BUILD_NUMBER }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip
          asset_name: ${{ env.BUILD_OUTPUT }}-${{ env.BUILD_NUMBER }}.zip
          asset_content_type: application/zip
